import { GlobalContexProvider } from "./Context/store"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
        <body>
          <GlobalContexProvider>
            {children}
          </GlobalContexProvider>
          
        </body>
    </html>
  )
}
