services:
  backend:
    image: node:16.14-alpine
    container_name: backend_hall_events
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app-backend
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001    
    environment:
      DB_HOST: db 
      JWT_SECRET: JWT_SECRET
      DB_PORT: 3306
      DB_NAME: event_hall_management
      HOST: 'http://localhost'

# Serviço que irá rodar o banco de dados
  db:
    container_name: db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s      